-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.meta_option
(
    id serial NOT NULL,
    "metaValue" json NOT NULL,
    "createDate" timestamp without time zone NOT NULL DEFAULT now(),
    "updateDate" timestamp without time zone NOT NULL DEFAULT now(),
    "postId" integer,
    CONSTRAINT "PK_59e834d6ba39bd9bd7c99b8805d" PRIMARY KEY (id),
    CONSTRAINT "REL_b492d76365f19dffc4d60a7f86" UNIQUE ("postId")
);

CREATE TABLE IF NOT EXISTS public.post
(
    id serial NOT NULL,
    title character varying(512) COLLATE pg_catalog."default" NOT NULL,
    "postType" post_posttype_enum NOT NULL DEFAULT 'post'::post_posttype_enum,
    slug character varying(256) COLLATE pg_catalog."default" NOT NULL,
    status post_status_enum NOT NULL DEFAULT 'draft'::post_status_enum,
    content text COLLATE pg_catalog."default",
    schema text COLLATE pg_catalog."default" NOT NULL,
    "featuredImageUrl" character varying(1024) COLLATE pg_catalog."default",
    "publishOn" timestamp without time zone,
    "authorId" integer,
    CONSTRAINT "PK_be5fda3aac270b134ff9c21cdee" PRIMARY KEY (id),
    CONSTRAINT "UQ_cd1bddce36edc3e766798eab376" UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.post_tags_tag
(
    "postId" integer NOT NULL,
    "tagId" integer NOT NULL,
    CONSTRAINT "PK_e9b7b8e6a07bdccb6a954171676" PRIMARY KEY ("postId", "tagId")
);

CREATE TABLE IF NOT EXISTS public.tag
(
    id serial NOT NULL,
    name character varying(256) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(256) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    schema text COLLATE pg_catalog."default",
    "featuredImageUrl" character varying(1024) COLLATE pg_catalog."default",
    "createDate" timestamp without time zone NOT NULL DEFAULT now(),
    "updateDate" timestamp without time zone NOT NULL DEFAULT now(),
    "deletedAt" timestamp without time zone,
    CONSTRAINT "PK_8e4052373c579afc1471f526760" PRIMARY KEY (id),
    CONSTRAINT "UQ_3413aed3ecde54f832c4f44f045" UNIQUE (slug),
    CONSTRAINT "UQ_6a9775008add570dc3e5a0bab7b" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.upload
(
    id serial NOT NULL,
    name character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    path character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    type upload_type_enum NOT NULL DEFAULT 'image'::upload_type_enum,
    mime character varying(128) COLLATE pg_catalog."default" NOT NULL,
    size character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "createDate" timestamp without time zone NOT NULL DEFAULT now(),
    "updateDate" timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_1fe8db121b3de4ddfa677fc51f3" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id serial NOT NULL,
    "firstName" character varying(96) COLLATE pg_catalog."default" NOT NULL,
    "lastName" character varying(96) COLLATE pg_catalog."default",
    email character varying(96) COLLATE pg_catalog."default" NOT NULL,
    password character varying(96) COLLATE pg_catalog."default",
    "googleId" character varying COLLATE pg_catalog."default",
    CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY (id),
    CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE (email)
);

ALTER TABLE IF EXISTS public.meta_option
    ADD CONSTRAINT "FK_b492d76365f19dffc4d60a7f863" FOREIGN KEY ("postId")
    REFERENCES public.post (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "REL_b492d76365f19dffc4d60a7f86"
    ON public.meta_option("postId");


ALTER TABLE IF EXISTS public.post
    ADD CONSTRAINT "FK_c6fb082a3114f35d0cc27c518e0" FOREIGN KEY ("authorId")
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.post_tags_tag
    ADD CONSTRAINT "FK_41e7626b9cc03c5c65812ae55e8" FOREIGN KEY ("tagId")
    REFERENCES public.tag (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_41e7626b9cc03c5c65812ae55e"
    ON public.post_tags_tag("tagId");


ALTER TABLE IF EXISTS public.post_tags_tag
    ADD CONSTRAINT "FK_b651178cc41334544a7a9601c45" FOREIGN KEY ("postId")
    REFERENCES public.post (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_b651178cc41334544a7a9601c4"
    ON public.post_tags_tag("postId");

END;